### ISSUE TITLE
Tags with no data

### ISSUE THREAD

**Issue by visualvibe** [Servoy/smartDocumentEditor#1]
If a tag does not have data from its corresponding record, it will leave a blank new line in the smart document editor. Is there anyway to not skip a line when a specific tag does not have data?

**Comment by seanthomasdevlin** [comment]
Hi Bjorn,

This issue will be addressed in:
https://support.servoy.com/browse/SVYX-306
Please subscribe as a "watcher" to receive updates. This GitHub issue will be updated with status changes.

Best,
Sean
